// For serving functions locally

const Dotenv = require('dotenv-webpack');

// @see https://github.com/netlify/netlify-lambda#webpack-configuration
module.exports = {
  plugins: [new Dotenv()],
  externals: [
    'atpl',
    'bracket',
    'dot',
    'doT.js',
    'dust',
    'dustjs-linkedin',
    'eco',
    'ect',
    'ejs',
    'haml',
    'haml-coffee',
    'hamlet',
    'hiredis',
    'hogan',
    'htmling',
    'jade',
    'jazz',
    'jqtpl',
    'just',
    'liquor',
    'marko',
    'mote',
    'mustache',
    'nunjucks',
    'plates',
    'pug',
    'QEJS',
    'ractive',
    'react',
    'slm',
    'swig',
    'swig',
    'teacup',
    'templayed',
    'twig',
    'liquid',
    'toffee',
    'underscore',
    'vash',
    'walrus',
    'whiskers',
    'bracket-template',
    'hamljs',
    'hogan.js',
    'react-dom/server',
    'tinyliquid',
    'lodash',
    'handlebars',
  ],
};
