// @see https://github.com/netlify/netlify-lambda#webpack-configuration
const webpack = require('webpack');

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      CONTEXT: JSON.stringify(process.env.CONTEXT),
      MONGO_URL: JSON.stringify(process.env.MONGO_URL),
      MAILGUN_URL: JSON.stringify(process.env.MAILGUN_URL),
      MAILGUN_API_KEY: JSON.stringify(process.env.MAILGUN_API_KEY),
    }),
  ],
  externals: [
    'atpl',
    'bracket',
    'dot',
    'doT.js',
    'dust',
    'dustjs-linkedin',
    'eco',
    'ect',
    'ejs',
    'haml',
    'haml-coffee',
    'hamlet',
    'hiredis',
    'hogan',
    'htmling',
    'jade',
    'jazz',
    'jqtpl',
    'just',
    'liquor',
    'marko',
    'mote',
    'mustache',
    'nunjucks',
    'plates',
    'pug',
    'QEJS',
    'ractive',
    'react',
    'slm',
    'swig',
    'swig',
    'teacup',
    'templayed',
    'twig',
    'liquid',
    'toffee',
    'underscore',
    'vash',
    'walrus',
    'whiskers',
    'bracket-template',
    'hamljs',
    'hogan.js',
    'react-dom/server',
    'tinyliquid',
    'lodash',
    'handlebars',
  ],
};
